"""add post image fields

Revision ID: 57439910ab07
Revises: a6b2f30e45e9
Create Date: 2026-08-09 13:54:57.165821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57439910ab07'
down_revision: Union[str, Sequence[str], None] = 'a6b2f30e45e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('posts', sa.Column('image_name', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('image_type', sa.String(length=100), nullable=True))
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_type')
    op.drop_column('posts', 'image_name')
    op.drop_column('posts', 'image_data')
    # ### end Alembic commands ###
